Feature/cs4360 288 invoice model
hiddentemple/4360techproject pull request #58
Opened 2020-11-17 01:26 UTC by jjohnson509

working invoice service/model/controller

2020-11-21 00:13 UTC, Newms226 requested changes
Please comment on changes and let me know if you think its ready to merge :)

2020-11-21 16:17 UTC, jjohnson509 commented on pb-crm-api/src/db/entities/payment.entity.ts
> +  account: AccountEntity;
this is the inverse relation, and doesnt do validation. you cant really post payment info with an account. but can post an account with payment info, so the validation would come from the account entity.

2020-11-21 16:19 UTC, jjohnson509 commented on pb-crm-api/src/contact/services/address.service.ts
> +    const newAddress: AddressEntity = entityManager.create<AddressEntity>(AddressEntity, { ...dto });
good catch, mistakenly left if out. added it back in.

2020-11-25 02:38 UTC, jjohnson509 commented
Everything should be good, I made changes, and left comments where appropriate. @Newms226

2020-11-29 01:49 UTC, Newms226 commented on pb-crm-api/src/db/entities/payment.entity.ts
> +  account: AccountEntity;
👍🏼

2020-11-29 01:50 UTC, Newms226 approved these changes
Changes look great, merging now

2020-11-29 01:50 UTC, merged