Feature/cs4360 361 ng account service
hiddentemple/4360techproject pull request #61
Opened 2020-11-27 19:28 UTC by GitNickProgramming

2020-11-27 22:59 UTC, Newms226 requested changes
Please address my comments and send a message in discord once fixed.

Looks great :)

2020-11-27 22:59 UTC, Newms226 commented on pb-crm-ui/src/app/invoicing/services/account.service.ts
> +export class ContactService {
All the routes in this class are pointing to contact. Also this class is not named correctly.

2020-11-27 22:59 UTC, Newms226 commented on pb-crm-ui/src/app/invoicing/services/account.service.ts
> +} from '@hiddentemple/api-interfaces';
You should run an organize imports to clean this up

2020-11-27 22:59 UTC, Newms226 commented on pb-crm-ui/src/app/invoicing/services/account.service.ts
> +  }
Remove all this functionality please

2020-11-30 18:01 UTC, closed without merging

2020-11-30 18:01 UTC, GitNickProgramming commented
Resubmitting